sudo: required
language: ruby
services:
- docker
script:
- docker build -t fingershock/elasticmq .
- docker run --rm fingershock/elasticmq java -version 
notifications:
  slack:
    secure: iM9+B44GcwxcqRltmUdos0wEAAlC+/RKmRz6KaI88MM9BateDmFAZlY8kqMfDjtUGVoF14ggOCNpnSUNxsX15eyI9qNFTv2cs+BxSsZqVIXZjJtn5h97ROyvQ+ZPBmDMfV6VHYIe52AjKzyODfe4UJ2raRQ1fYRw3AAf77R6bJYnOlhKwzppM7dNMl9yuTfAbpdvqEdRdagRs9gfc6G754cgypo5PWJFCiIFNUZIpiI17Dr/38MFCFUMfYNcC/ybd/g/W1FPMwVGUxTRbmasmI/SPV9SKJITjTDGxGYEIlIK8BrEgj2JlGgANDD0hseuJweFZBaO0fgSgyrDqUT7uiM6YliQKxpDs+jhRe2dDVWh1/osVBWq7J/W0sqW808D4XzEnRGFM/A9oDytqRdFlRNkQ+vEH9EGqHRLizKq/oJ6PVUQL7rRIT2Utv6Jze2jOfNdmMOuBkEcPR6SCUwip2KI79r/GQeRMKxd12PiI8J2WKUa6UFrhdGK/9e2DAnO+ZTo3prz73J9kH1Nf5bNPUj6EX9Z4XVlwUBCVrOsaRWdSJCUFya7Zq0Vt3SJ9aBGQQIxGd8vBJ6zhAwzYYKqw1R2dpLK6ADEzEYB+nSIjcpvCGbZx1spfA8B5GHzMPbPnaDleU5ixLsWOOzRcVi0NvTHUVOMQcgDZHi8hXtcg7s=
